name: bus_buddy_user
description: Bus Tracking User application made using Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  font_awesome_flutter: ^10.5.0
  firebase_analytics: ^10.5.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_database: ^10.2.7
  firebase_messaging: ^14.6.8
  firebase_storage: ^11.2.7
  flutter_bloc: ^8.1.3
  flutter_map: ^6.0.0
  flutter_typeahead: ^4.8.0
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  go_router: ^11.1.2
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  lottie: ^2.6.0
  package_info_plus: ^4.1.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/lottie/
     - assets/images/